= LaTeX-unicode-math-mode

This is an emacs minor mode for entering unicode math symbols in
LaTeX-mode (provided by auctex).  It automatically replaces inputs
like `\phi` with `φ` and `\in` with `∈`.  These replacements happen
inside of math environments or everywhere, depending on the
configuration.

You probably want to add `\usepackage{unicode-math-mode}` to your tex
file make to LaTeX aware of the unicode characters.

Add this to your emacs configuration somewhere *after* loading auctex:
----
(add-to-list 'load-path "path/to/LaTeX-unicode-math-mode")
(require 'LaTeX-unicode-math-mode)

;; Enable LaTeX-unicode-math-mode automatically for all LaTeX files.
;; This converts LaTeX to unicode inside math environments.
(add-hook 'LaTeX-mode-hook 'LaTeX-unicode-math-mode)

;; Enable LaTeX-unicode-global-mode automatically for all LaTeX files.
;; This converts LaTeX to unicode everwhere, not only in math
;; environments.
;;(add-hook 'LaTeX-mode-hook 'LaTeX-unicode-global-mode)
----

Note that `LaTeX-unicode-math-mode` and `LaTeX-unicode-global-mode`
are mutually exclusive.  Enabling one will automatically disable the
other.

Tested with pdflatex from TeX Live 2015 and GNU Emacs 24.5.1.

== Additional Features

`M-x LaTeX-unicode-math-convert-region` converts all LaTeX macros in
the active region to their unicode equivalents.

`M-x LaTeX-unicode-math-convert-buffer` converts the whole buffer.

== Bugs

Due to the implementation, this minor mode will probably break your
input method.  If you do not know what an input method is or if you
write in English or in another European language, chances are you are
not using one.
