= LaTeX-unicode-math-mode

This is an emacs minor mode for entering unicode math symbols in
LaTeX-mode (provided by auctex).  It automatically replaces inputs
like `\phi` with `φ` and `\in` with `∈`.  These replacements happen
inside of math environments or everywhere, depending on the
configuration.

If you use pdflatex, you probably want to add
`\usepackage{unicode-math-mode}` to your tex file in order to make
pdflatex aware of the unicode characters.  For XeTeX, this may be
different.

Add this to your emacs configuration somewhere *after* loading auctex:
----
(add-to-list 'load-path "path/to/LaTeX-unicode-math-mode")
(require 'LaTeX-unicode-math-mode)

;; Enable LaTeX-unicode-math-mode automatically for all LaTeX files.
;; This converts LaTeX to unicode inside math environments.
(add-hook 'LaTeX-mode-hook 'LaTeX-unicode-math-mode)

;; Enable LaTeX-unicode-global-mode automatically for all LaTeX files.
;; This converts LaTeX to unicode everwhere, not only in math
;; environments.
;;(add-hook 'LaTeX-mode-hook 'LaTeX-unicode-global-mode)
----

Note that `LaTeX-unicode-math-mode` and `LaTeX-unicode-global-mode`
are mutually exclusive.  Enabling one will automatically disable the
other.

Tested with pdflatex from TeX Live 2015 and GNU Emacs 24.5.1.

== Example

Say you type this:
[source,latex]
----
In the following definitions, let $P = (V,E,V_\even,\omega)$ be a
parity game and $i$ be a player.

\begin{definition}[Strategy]
  A strategy for player~$i$ is a function $\pi: V^*V_i \to V$ such that
  $(\seq v, \pi(\seq v)) \in E$ for all paths $\seq v \in V^*V_i$.
\end{definition}
\begin{definition}[$\pi$-Conforming Path]
  We say that a path $\seq v = (v_1,v_2,\ldots) \in V^+ \cup V^\omega$
  (finite or infinite) is \emph{$\pi$-conforming} to a strategy $\pi$
  if $v_{k+1} = \pi(v_1,\ldots,v_k)$ holds for all its proper initial
  segments $(v_1,\ldots,v_k) \in V^*V_i$.
\end{definition}
----

As you type, `LaTeX-unicode-math-mode` turns it into this:
[source,latex]
----
In the following definitions, let $P = (V,E,V_\even,ω)$ be a
parity game and $i$ be a player.

\begin{definition}[Strategy]
  A strategy for player~$i$ is a function $π: V^*V_i \to V$ such that
  $(\seq v, π(\seq v)) ∈ E$ for all paths $\seq v ∈ V^*V_i$.
\end{definition}
\begin{definition}[$π$-Conforming Path]
  We say that a path $\seq v = (v_1,v_2,…) ∈ V^+ ∪ V^ω$
  (finite or infinite) is \emph{$π$-conforming} to a strategy $π$
  if $v_{k+1} = π(v_1,…,v_k)$ holds for all its proper initial
  segments $(v_1,…,v_k) ∈ V^*V_i$.
\end{definition}
----

== Additional Features

`M-x LaTeX-unicode-math-convert-region` converts all LaTeX macros in
the active region to their unicode equivalents.

`M-x LaTeX-unicode-math-convert-buffer` is the same, but applies to
the whole buffer.

`M-x LaTeX-unicode-math-invert-region` and `M-x
LaTeX-unicode-math-invert-buffer` revert all unicode symbols in the
current region/buffer back to their LaTeX equivalents.

== Bugs

Due to the implementation, this minor mode will probably break your
input method.  If you do not know what an input method is or if you
write in English or in another European language, chances are you are
not using one.
